language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
script: mvn clean install -U
install: true
notifications:
  email:
    recipients:
      - "dmulloy2@live.com"
    on_success: change
    on_failure: always