global:
  # Settings for the automatic version updater
  auto updater:
    notify: true
    download: true
    
    # Number of seconds to wait until a new update is downloaded
    delay: 43200 # 12 hours
    # Last update time
    last: 0