name: ProtocolLib
version: 1.4.4-SNAPSHOT
description: Provides read/write access to the Minecraft protocol.
author: Comphenix
website: http://www.comphenix.net/ProtocolLib

main: com.comphenix.protocol.ProtocolLibrary
database: false